# integrative command interface
[[plugins]]
repo = 'Shougo/unite.vim'
if = '!has("nvim")'
on_cmd = [ 'Unite', 'UniteResume', ]

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim")'
hook_add = 'call float#init#denite#hook_add()'
on_cmd = [ 'Denite', 'DeniteResume', ]

[[plugins]]
repo = 'Shougo/neomru.vim'
on_cmd = [ 'Unite', 'UniteResume', 'DeniteResume', 'DeniteResume', ]


# file explorer
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'call float#init#nerdtree#hook_add()'
on_cmd = [ 'NERDTreeToggle', 'NERDTree', ]


# open in browser
[[plugins]]
repo = 'tyru/open-browser.vim'
on_cmd = [ 'OpenBrowser', 'OpenBrowserSearch', ]
on_mappings = [ '<Plug>(openbrowser-smart-search)', ]
hook_source = '''
    let g:netrw_nogx = 1
'''


# color code highlighting
[[plugins]]
repo = 'chrisbra/Colorizer'
on_cmd = [ 'ColorToggle', 'ColorHighlight', 'ColorContrast', ]


# code execution
[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = [ 'QuickRun', ]
hook_add    = 'call float#init#quickrun#hook_add()'
hook_source = 'call float#init#quickrun#hook_source()'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
on_source = [ 'vim-quickrun', ]


# auto complete of surrouindings
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1


# deoplete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_source = 'call float#init#deoplete#hook_source()'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = '!has("nvim") && has("lua")'
on_i = 1
hook_source = 'call float#init#neocomplete#hook_source()'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_source = [ 'deoplete.nvim', 'neocomplete.vim', ]

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_source = [ 'neosnippet.vim', ]



# filetype support
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = [ 'toml', ]

[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = [ 'c', 'cpp' ]
hook_source = 'call float#init#clang-format#hook_source()'

